# RT - Data

# シャードIDのリストです。`auto`の場合は全自動となります。
shard_ids = "auto"
# シャードの数です。`shard_ids`を`auto`にした場合は未入力で良いです。
shard_count = ""
# Opusのライブラリのパスです。Windowsの場合は未指定で大丈夫です。
# Unixの場合は`"opus"`と指定してください。それでも動かない場合は直のパスを指定してください。
opus = ""

[backend]
# バックエンドの情報です。バックエンドにアクセスするのに使います。
host = "rt-bot-test.com"
port = 8080