# RT - Data

# 接続するBotのTOKENです。
token = "..."

[mysql]
# MySQLへの接続情報です。
# aiomysqlというライブラリの`create_pool`という関数にキーワード引数として以下が渡されます。
host = "localhost"
user = "rt-bot"
password = "..."
db = "rtdb"
autocommit = true