name: Report bug(バグの報告)
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Bug報告をしてください。
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: また、生じると期待されていたことは何でしょうか？
      placeholder: Tell us what you see!
      value: "バグが生じました!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: `python -m discord -v` shellでこれを実行してください。
      placeholder: >
        Example:
          - Python v3.10.5-final
          - discord.py v2.0.0-alpha
          - discord.py pkg_resources: v2.0.0a4354+g96e6261d
          - aiohttp v3.8.0
          - system info: Linux 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: 関連するログの出力をコピーしてペーストしてください。 これは自動的にコードにフォーマットされるので、バックティックは不要です。
      render: shell
