name: Report bug(バグの報告)
description: File a bug report
title: ""
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        バグ報告をしてください。
        Please file a bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: >
        何が起きたかの詳細と、予期していた動作をお書きください。
        Please provide details of what happened and the expected behavior.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >
        `python -m discord -v` shellでこれを実行してください。
        Run this in `python -m discord -v` shell.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        関連するログの出力をコピーしてペーストしてください。 これは自動的にコードにフォーマットされるので、バックティックは不要です。
        Copy and paste the relevant log output. This is automatically formatted into code, so no backticks are required.
      render: shell
