name: New feature or request(主に機能提案)
description: 機能提案を行う場所です。追加するかどうかは分かりません。
title: "[Enhancement]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        機能提案をここで指示されているとおりにやってください。
  - type: textarea
    id: description
    attributes:
      label: Please asked me.
      description: 機能の詳細をここで話してください。
      placeholder: Tell us what you see!
    validations:
      required: true
