name: Others
description: >
  割り振りがしずらいものです。
  It is something that is hard to assign.

body:
  - type: markdown
    attributes:
      value: |
        Issueをどうぞ。
  - type: textarea
    id: describe
    attributes:
      label: Describe
    validations:
      required: true
