name: Others
description: >
  割り振りがしずらいものです。
  It is something that is hard to assign.
title: ""
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
    validations:
      required: true