name: others(その他)
description: これらにない場合はこちらを使ってください。
title: "[Others]: "
body:
  - type: markdown
    attributes:
      value: |
        主にバグや機能提案ではない場合のみ使います。
  - type: textarea
    id: describe
    attributes:
      label: describe
      description: ここに内容を書き込んでください。
    validations:
      required: true
